parameters:
#    yr_users.example.class: YR\UsersBundle\Example

services:
#    yr_users.example:
#        class: %yr_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
